MYSQL_ROOT_USER: root
MYSQL_ROOT_PASSWORD: RoboShop@1
version: 1.0
USER_HOST : user.suneel.shop
CART_HOST : cart.suneel.shop
SHIPPING_HOST : shipping.suneel.shop
PAYMENT_HOST : payment.suneel.shop
MONGODB_HOST : mongodb.suneel.shop
MYSQL_HOST : mysql.suneel.shop
RABBITMQ_HOST : rabbitmq.suneel.shop
CATALOGUE_HOST : catalogue.suneel.shop
REDIS_HOST : redis.suneel.shop
