- name : app setup 
  ansible.builtin.import_role:
    name : common 
    tasks_from : appsetup


- name : nodejs
  ansible.builtin.import_role:
    name : common
    tasks_from : nodejs

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemsetup.yaml

