- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup.yaml

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemsetup.yaml
    