- name : installing mysql server
  ansible.builtin.package:
    name : mysql-server
    state : present

- name : enabling mysql
  ansible.builtin.service:
    name : mysqld
    enabled : yes 
    state : started 

- name : setting up root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1