- name : nodejs setup
  ansible.builtin.import_role:
    name : common
    tasks_from : nodejs.yaml

- name : app setup 
  ansible.builtin.import_role:
    name : common
    tasks_from : appsetup.yaml

- name : syetem setup
  ansible.builtin.import_role:
    name : common
    tasks_from : systemsetup.yaml
  
